spring:
  application:
    name: SB-JPA-02-findByXXX
    
  datasource:
    url:   jdbc:mysql://localhost:3306/springboot
    
    username: root
    
    password: MYSQL
    
  jpa:
    hibernate:
      ddl-auto: update
      
    show-sql: true

    