spring:
  application:
    name: SB-JPA-05-Sorting
    
  datasource:
    url:   jdbc:mysql://localhost:3306/springboot
    
    username: root
    
    password: MYSQL
    
  jpa:
    hibernate:
      ddl-auto: update
      
    show-sql: true
  sql:
    init:
      platform: org.hibernate.dialect.MySQL8nnoDBDialect

    
